export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_COMPLETE = 'GET_ALL_JOBS_COMPLETE';
export const GET_ALL_JOBS_ERROR = 'GET_ALL_JOBS_ERROR';

export const CHECK_JOB_NAME_REQUEST = 'CHECK_JOB_NAME_REQUEST';
export const CHECK_JOB_NAME_COMPLETE = 'CHECK_JOB_NAME_COMPLETE';
export const CHECK_JOB_NAME_ERROR = 'CHECK_JOB_NAME_ERROR';

export const EDIT_JOB_START = 'EDIT_JOB_START';
export const UPDATE_BEING_EDITED_JOB = 'UPDATE_BEING_EDITED_JOB';
export const UPDATE_EDIT_JOB_MODAL_DATA = 'UPDATE_EDIT_JOB_MODAL_DATA';
export const EDIT_JOB_CLOSE = 'EDIT_JOB_CLOSE';

export const SHOW_CREATE_JOB_MODAL = 'SHOW_CREATE_JOB_MODAL';
export const HIDE_CREATE_JOB_MODAL = 'HIDE_CREATE_JOB_MODAL';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_COMPLETE = 'CREATE_JOB_COMPLETE';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';


export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_COMPLETE = 'UPDATE_JOB_COMPLETE';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_COMPLETE = 'DELETE_JOB_COMPLETE';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';


export const CREATE_BUILD = 'CREATE_BUILD';
export const UPDATE_JOB_BUILD_DATA = 'UPDATE_JOB_BUILD_DATA';

export const GET_ALL_CREDENTIALS_REQUEST = 'GET_ALL_CREDENTIALS_REQUEST';
export const GET_ALL_CREDENTIALS_COMPLETE = 'GET_ALL_CREDENTIALS_COMPLETE';
export const GET_ALL_CREDENTIALS_ERROR = 'GET_ALL_CREDENTIALS_ERROR';

export const CHECK_CREDENTIAL_NAME_REQUEST = 'CHECK_CREDENTIAL_NAME_REQUEST';
export const CHECK_CREDENTIAL_NAME_COMPLETE = 'CHECK_CREDENTIAL_NAME_COMPLETE';
export const CHECK_CREDENTIAL_NAME_ERROR = 'CHECK_CREDENTIAL_NAME_ERROR';


export const EDIT_CREDENTIAL_START = 'EDIT_CREDENTIAL_START';
export const UPDATE_BEING_EDITED_CREDENTIAL = 'UPDATE_BEING_EDITED_CREDENTIAL';
export const EDIT_CREDENTIAL_CLOSE = 'EDIT_CREDENTIAL_CLOSE';

export const CREATE_CREDENTIAL_REQUEST = 'CREATE_CREDENTIAL_REQUEST';
export const CREATE_CREDENTIAL_COMPLETE = 'CREATE_CREDENTIAL_COMPLETE';
export const CREATE_CREDENTIAL_ERROR = 'CREATE_CREDENTIAL_ERROR';

export const UPDATE_CREDENTIAL_REQUEST = 'UPDATE_CREDENTIAL_REQUEST';
export const UPDATE_CREDENTIAL_COMPLETE = 'UPDATE_CREDENTIAL_COMPLETE';
export const UPDATE_CREDENTIAL_ERROR = 'UPDATE_CREDENTIAL_ERROR';

export const DELETE_CREDENTIAL_REQUEST = 'DELETE_CREDENTIAL_REQUEST';
export const DELETE_CREDENTIAL_COMPLETE = 'DELETE_CREDENTIAL_COMPLETE';
export const DELETE_CREDENTIAL_ERROR = 'DELETE_CREDENTIAL_ERROR';

export const PLAY_JOB_REQUEST = 'PLAY_JOB_REQUEST';
export const PLAY_JOB_COMPLETE = 'PLAY_JOB_COMPLETE';
export const PLAY_JOB_ERROR = 'PLAY_JOB_ERROR';

export const GET_JOB_DETAILS_REQUEST = 'GET_JOB_DETAILS_REQUEST';
export const GET_JOB_DETAILS_COMPLETE = 'GET_JOB_DETAILS_COMPLETE';
export const GET_JOB_DETAILS_ERROR = 'GET_JOB_DETAILS_ERROR';

export const GET_BUILD_DETAILS_REQUEST = 'GET_BUILD_DETAILS_REQUEST';
export const GET_BUILD_DETAILS_COMPLETE = 'GET_BUILD_DETAILS_COMPLETE';
export const GET_BUILD_DETAILS_ERROR = 'GET_BUILD_DETAILS_ERROR';

export const READ_LOG = 'READ_LOG';
export const CANCEL_READ_LOG = 'CANCEL_READ_LOG';
export const RECEIVE_LOG = 'RECEIVE_LOG';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const OPEN_ADD_AGENT_MODAL = 'OPEN_ADD_AGENT_MODAL';
export const CLOSE_ADD_AGENT_MODAL = 'CLOSE_ADD_AGENT_MODAL';
export const OPEN_EDIT_AGENT_MODEL = 'OPEN_EDIT_AGENT_MODEL';
export const CLOSE_EDIT_AGENT_MODAL = 'CLOSE_EDIT_AGENT_MODAL';

export const UPDATE_BEING_EDITED_AGENT = 'UPDATE_BEING_EDITED_AGENT';
export const UPDATE_EDIT_AGENT_MODAL_DATA = 'UPDATE_EDIT_AGENT_MODAL_DATA';

export const ADD_AGENT_REQUEST = 'ADD_AGENT_REQUEST';
export const ADD_AGENT_COMPLETE = 'ADD_AGENT_COMPLETE';
export const ADD_AGENT_ERROR = 'ADD_AGENT_ERROR';

export const GET_ALL_AGENTS_REQUEST = 'GET_ALL_AGENTS_REQUEST';
export const GET_ALL_AGENTS_COMPLETE = 'GET_ALL_AGENTS_COMPLETE';
export const GET_ALL_AGENTS_ERROR = 'GET_ALL_AGENTS_ERROR';

export const UPDATE_AGENT_REQUEST = 'UPDATE_AGENT_REQUEST';
export const UPDATE_AGENT_COMPLETE = 'UPDATE_AGENT_COMPLETE';
export const UPDATE_AGENT_ERROR = 'UPDATE_AGENT_ERROR';

export const CHECK_AGENT_NAME_REQUEST = 'CHECK_AGENT_NAME_REQUEST';
export const CHECK_AGENT_NAME_COMPLETE = 'CHECK_AGENT_NAME_COMPLETE';
export const CHECK_AGENT_NAME_ERROR = 'CHECK_AGENT_NAME_ERROR';

export const DELETE_AGENT_REQUEST = 'DELETE_AGENT_REQUEST';
export const DELETE_AGENT_COMPLETE = 'DELETE_AGENT_COMPLETE';
export const DELETE_AGENT_ERROR = 'DELETE_AGENT_ERROR';

export const EDIT_AGENT_IMMEDIATELY = 'EDIT_AGENT_IMMEDIATELY';