export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_COMPLETE = 'GET_ALL_JOBS_COMPLETE';
export const GET_ALL_JOBS_ERROR = 'GET_ALL_JOBS_ERROR';

export const GET_JOB_BY_NAME_REQUEST = 'GET_JOB_BY_NAME_REQUEST';
export const GET_JOB_BY_NAME_COMPLETE = 'GET_JOB_BY_NAME_COMPLETE';
export const GET_JOB_BY_NAME_ERROR = 'GET_JOB_BY_NAME_ERROR';

export const CREATE_JOB_START = 'CREATE_JOB_START';
export const CREATE_JOB_CANCEL = 'CREATE_JOB_CANCEL';
export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_COMPLETE = 'CREATE_JOB_COMPLETE';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_ALL_GITHUB_ACCOUNTS_REQUEST = 'GET_ALL_GITHUB_ACCOUNTS_REQUEST';
export const GET_ALL_GITHUB_ACCOUNTS_COMPLETE = 'GET_ALL_GITHUB_ACCOUNTS_COMPLETE';
export const GET_ALL_GITHUB_ACCOUNTS_ERROR = 'GET_ALL_GITHUB_ACCOUNTS_ERROR';

export const GET_REPOS_FOR_GITHUB_ACCOUNTS_REQUEST = 'GET_REPOS_FOR_GITHUB_ACCOUNTS_REQUEST';
export const GET_REPOS_FOR_GITHUB_ACCOUNTS_COMPLETE = 'GET_REPOS_FOR_GITHUB_ACCOUNTS_COMPLETE';
export const GET_REPOS_FOR_GITHUB_ACCOUNTS_ERROR = 'GET_REPOS_FOR_GITHUB_ACCOUNTS_ERROR';

export const SET_PAGE = 'SET_PAGE';

export const GET_BRANCHES_FOR_REPO_REQUEST = 'GET_BRANCHES_FOR_REPO_REQUEST';
export const GET_BRANCHES_FOR_REPO_COMPLETE = 'GET_BRANCHES_FOR_REPO_COMPLETE';
export const GET_BRANCHES_FOR_REPO_ERROR = 'GET_BRANCHES_FOR_REPO_ERROR';

export const SELECT_BRANCH = 'SELECT_BRANCH'