export const GET_ALL_JOBS_REQUEST = 'GET_ALL_JOBS_REQUEST';
export const GET_ALL_JOBS_COMPLETE = 'GET_ALL_JOBS_COMPLETE';
export const GET_ALL_JOBS_ERROR = 'GET_ALL_JOBS_ERROR';

export const CHECK_JOB_NAME_REQUEST = 'CHECK_JOB_NAME_REQUEST';
export const CHECK_JOB_NAME_COMPLETE = 'CHECK_JOB_NAME_COMPLETE';
export const CHECK_JOB_NAME_ERROR = 'CHECK_JOB_NAME_ERROR';

export const EDIT_JOB_START = 'EDIT_JOB_START';
export const UPDATE_BEING_EDITED_JOB = 'UPDATE_BEING_EDITED_JOB';
export const UPDATE_EDIT_JOB_FORM_DATA = 'UPDATE_EDIT_JOB_FORM_DATA';
export const EDIT_JOB_CLOSE = 'EDIT_JOB_CLOSE';

export const SHOW_CREATE_JOB_MODAL = 'SHOW_CREATE_JOB_MODAL';
export const HIDE_CREATE_JOB_MODAL = 'HIDE_CREATE_JOB_MODAL';

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST';
export const CREATE_JOB_COMPLETE = 'CREATE_JOB_COMPLETE';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';


export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST';
export const UPDATE_JOB_COMPLETE = 'UPDATE_JOB_COMPLETE';
export const UPDATE_JOB_ERROR = 'UPDATE_JOB_ERROR';

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST';
export const DELETE_JOB_COMPLETE = 'DELETE_JOB_COMPLETE';
export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';


export const CREATE_BUILD = 'CREATE_BUILD';
export const UPDATE_JOB_BUILD_DATA = 'UPDATE_JOB_BUILD_DATA';

export const GET_ALL_CREDENTIALS_REQUEST = 'GET_ALL_CREDENTIALS_REQUEST';
export const GET_ALL_CREDENTIALS_COMPLETE = 'GET_ALL_CREDENTIALS_COMPLETE';
export const GET_ALL_CREDENTIALS_ERROR = 'GET_ALL_CREDENTIALS_ERROR';

export const CHECK_CREDENTIAL_NAME_REQUEST = 'CHECK_CREDENTIAL_NAME_REQUEST';
export const CHECK_CREDENTIAL_NAME_COMPLETE = 'CHECK_CREDENTIAL_NAME_COMPLETE';
export const CHECK_CREDENTIAL_NAME_ERROR = 'CHECK_CREDENTIAL_NAME_ERROR';


export const EDIT_CREDENTIAL_START = 'EDIT_CREDENTIAL_START';
export const UPDATE_BEING_EDITED_CREDENTIAL = 'UPDATE_BEING_EDITED_CREDENTIAL';
export const EDIT_CREDENTIAL_CLOSE = 'EDIT_CREDENTIAL_CLOSE';

export const CREATE_CREDENTIAL_REQUEST = 'CREATE_CREDENTIAL_REQUEST';
export const CREATE_CREDENTIAL_COMPLETE = 'CREATE_CREDENTIAL_COMPLETE';
export const CREATE_CREDENTIAL_ERROR = 'CREATE_CREDENTIAL_ERROR';

export const UPDATE_CREDENTIAL_REQUEST = 'UPDATE_CREDENTIAL_REQUEST';
export const UPDATE_CREDENTIAL_COMPLETE = 'UPDATE_CREDENTIAL_COMPLETE';
export const UPDATE_CREDENTIAL_ERROR = 'UPDATE_CREDENTIAL_ERROR';

export const DELETE_CREDENTIAL_REQUEST = 'DELETE_CREDENTIAL_REQUEST';
export const DELETE_CREDENTIAL_COMPLETE = 'DELETE_CREDENTIAL_COMPLETE';
export const DELETE_CREDENTIAL_ERROR = 'DELETE_CREDENTIAL_ERROR';

export const PLAY_JOB_REQUEST = 'PLAY_JOB_REQUEST';
export const PLAY_JOB_COMPLETE = 'PLAY_JOB_COMPLETE';
export const PLAY_JOB_ERROR = 'PLAY_JOB_ERROR';

export const GET_JOB_DETAILS_REQUEST = 'GET_JOB_DETAILS_REQUEST';
export const GET_JOB_DETAILS_COMPLETE = 'GET_JOB_DETAILS_COMPLETE';
export const GET_JOB_DETAILS_ERROR = 'GET_JOB_DETAILS_ERROR';

export const GET_BUILD_DETAILS_REQUEST = 'GET_BUILD_DETAILS_REQUEST';
export const GET_BUILD_DETAILS_COMPLETE = 'GET_BUILD_DETAILS_COMPLETE';
export const GET_BUILD_DETAILS_ERROR = 'GET_BUILD_DETAILS_ERROR';

export const READ_LOG = 'READ_LOG';
export const CANCEL_READ_LOG = 'CANCEL_READ_LOG';
export const RECEIVE_LOG = 'RECEIVE_LOG';